### ISSUE TITLE
Screen resolution incorrect on older model 2.8 resistive TFT

### ISSUE THREAD

**Issue by brownjohnf** [resin-io-playground/resin-wpe#2]
I've got one of these: https://www.adafruit.com/products/1601, and the screen is not scaling correctly. When loading https://resin.io, for example, I see the standard width layout, and only see the left-center part of the screen (the top and right sections appear cut off).

**Comment by brownjohnf** [comment]
![screenshot from 2017-04-04 12-34-32](https://cloud.githubusercontent.com/assets/1001049/24675446/060e9e62-1934-11e7-8ebc-762b3681df12.png)

Attaching a screenshot of my device configs.

**Comment by petrosagg** [comment]
@brownjohnf there is one error in your config, it should be `RESIN_HOST_CONFIG_force_hdmi_hotplug`. Can you try changing that and see if it fixes the issue?

Also keep in mind that webpages that would normally show a scrollbar when the window becomes small enough will appear cut off on WPE because there is no window manager to render the scrollbars.

This is known to work fine at 320x240 if you want to test. https://mrdoob.neocities.org/023/

**Comment by brownjohnf** [comment]
Nope, I've got the same issue with that gif. The center of the gif is roughly at the extreme upper right corner of the screen.

**Comment by petrosagg** [comment]
Hm, that's interesting. I'll try get one of those screens to test and see what's going on

**Comment by petrosagg** [comment]
The issue was due to running an old commit which used wayland for rendering. The current master build should work fine
